language: generic
sudo: required
services:
    -  docker
before_install:
    - docker build -t evgenijavstein/docker-react -f Dockerfile.dev .
script:
  - docker run -e CI=true evgenijavstein/docker-react npm run test -- --coverage